### ISSUE TITLE
Set expiration headers

### ISSUE THREAD

**Issue by ben-manes** [valery1707/javadoc-badge#2]
I released version 2.1.0 and the badge wasn't updated in the README. The [badge](https://javadoc-emblem.rhcloud.com/doc/com.github.ben-manes.caffeine/caffeine/badge.svg) served from your server is up to date, indicating that Github's image caching is the likely culprit. Because the expiration headers are not set, Github can cache the image indefinitely.

**Comment by valery1707** [comment]
For me badge https://github.com/ben-manes/caffeine now is updated.
In next release i will add expiration headers.
Thanks for hint

**Comment by ben-manes** [comment]
Yep, Github's image cache must have an 8 or 12 hour expiration window. The image updated a few hours after I posted this, but took much longer than other badges. Hence the guess that its using the HTTP header to detect if a smaller expiration window is required.

**Comment by ben-manes** [comment]
A little Googling shows a lot of various discussions regarding this, since many others providing badges ran into this same problem. It looks like CI badges use the `no-cache` pragma since the result should be immediate. For this badge either disabling HTTP caching or using a small time window seem like reasonable choices.

**Comment by valery1707** [comment]
i decided to set cache headers as half of the internal cache duration

**Comment by valery1707** [comment]
Currently it will be 1 hour

**Comment by v-nisidh** [comment]
@valery1707 : Can you verify my understanding is correct or not? 

After maven release, if I specifically went on http://javadoc.io/doc/com.microsoft.sqlserver/mssql-jdbc/6.1.7.jre8-preview (after appropriate updating version number as per maven release) then Javadoc.io will take couple of mins & able to show updated javadocs. 

After this if I click on badge (still showing wrong version) then it will open appropriate Javadoc. 

Then I open up new browser window and try to access badge text url i.e. http://javadoc.io/badge/com.microsoft.sqlserver/mssql-jdbc.svg 

it redirect and generates appropriate text using by shields.io. 

But now out GitHub readme page still shows old badge text. Do you think due to redirect it may ignore some http headers / ETags ? Did you see similar problem on any other project? 

Instead of redirect can you generate badge? ref: https://maven-badges.herokuapp.com/maven-central/com.microsoft.sqlserver/mssql-jdbc/badge.svg 

Even I saw similar behavior on last release. 


**Ref:** 
Unfortunately I saw old badge after releasing new release on Maven. I saw similar problem on our last release. Generally it will show old badge for ~ 2 days and then GitHub pages refresh the image. I did not see this with maven-badges.herokuapp.... 


https://github.com/Microsoft/mssql-jdbc 

Interesting thing is on normal browser it come up with appropriate badge. 
http://javadoc.io/badge/com.microsoft.sqlserver/mssql-jdbc.svg

While on GitHub, it is showing old badge but with correct link. Is it due to some redirection or appropriate cache-content headers ? 


[![Javadocs](http://javadoc.io/badge/com.microsoft.sqlserver/mssql-jdbc.svg)](http://javadoc.io/doc/com.microsoft.sqlserver/mssql-jdbc)

**Comment by ben-manes** [comment]
Note that you are using the badge provided directly by `javadoc.io`. @valery1707 project predated theirs, so he fixed the expiration problem. When I release my project, the badge updates after an hour or so.

**Comment by v-nisidh** [comment]
@ben-manes so in my case you are saying issue is with Javadoc.io. Am I right? I could not able to find any authenticate GitHub repo for Javadoc.io. https://github.com/search?utf8=%E2%9C%93&q=javadoc.io&type=

**Comment by ben-manes** [comment]
In the other issue, @Grogs said he had recently implemented an official badge (to replace @valery1707's). I was pointing out that the bug is an easy mistake, as it was made here too. Hopefully @Grogs will be notified and make the fix.

Alternatively, you could switch to @valery1707's badge since its equivalent.

**Comment by valery1707** [comment]
@v-nisidh this project is closed because OpenShit Online V2 is closed and this domain `javadoc-emblem.rhcloud.com` is not accessible anymore
